<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Macs-MacBook-Pro.local" failures="1" tests="2" name="Default test" time="75.35" errors="0" timestamp="2023-11-01T10:42:26 IST">
  <testcase classname="com.anhtester.projects.cms.testcases.ProfileTest" name="TC_UpdateProfile" time="39.246">
    <failure type="java.lang.AssertionError" message="The message not allowed in the demo is not displayedBy.xpath: //span[@data-notify=&amp;apos;message&amp;apos; and normalize-space() = &amp;apos;Sorry! the action is not permitted in demo&amp;apos;]">
      <![CDATA[java.lang.AssertionError: The message not allowed in the demo is not displayedBy.xpath: //span[@data-notify='message' and normalize-space() = 'Sorry! the action is not permitted in demo']
at org.testng.Assert.fail(Assert.java:111)
at com.anhtester.keywords.WebUI.verifyElementVisible(WebUI.java:2068)
at com.anhtester.projects.cms.users.pages.profiles.ProfilePage.updateProfile(ProfilePage.java:51)
at com.anhtester.projects.cms.testcases.ProfileTest.TC_UpdateProfile(ProfileTest.java:15)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TC_UpdateProfile -->
  <testcase classname="com.anhtester.projects.cms.testcases.ProfileTest" name="TC_AddNewAddress" time="27.077"/>
</testsuite> <!-- Default test -->
